function initMap(){
			var urlImg = 'http://netwebproyectos.com/francisco/gih2/';
			var latlng=new google.maps.LatLng(19.40283390560027,-99.17078444999999);
			var draggable=true;
			var myOptions={
				zoom:16,
				center:latlng,
				mapTypeId:google.maps.MapTypeId.ROADMAP,
				styles:[
					{
						"featureType":"administrative",
						"elementType":"geometry.fill",
						"stylers":[
							{
								"color":"#1e242b"
							},
							{
								"lightness":"5"
							}
								]
							},
							{
								"featureType":"administrative",
								"elementType":"geometry.stroke",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"saturation":"0"
								},
								{
									"lightness":"30"
								}
								]
							},
							{
								"featureType":"administrative",
								"elementType":"labels",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"30"
								}
								]
							},
							{
								"featureType":"administrative",
								"elementType":"labels.text.stroke",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							},
							{
								"featureType":"administrative.province",
								"elementType":"geometry.stroke",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"20"
								},
								{
									"weight":"1.00"
								}
								]
							},
							{
								"featureType":"administrative.neighborhood",
								"elementType":"labels.text.fill",
								"stylers":[
								{
									"lightness":"-20"
								}
								]
							},
							{
								"featureType":"administrative.land_parcel",
								"elementType":"labels.text.fill",
								"stylers":[
								{
									"lightness":"-20"
								}
								]
							},
							{
								"featureType":"landscape",
								"elementType":"geometry",
								"stylers":[
								{
									"color":"#1e242b"
								}
								]
							},
							{
								"featureType":"landscape",
								"elementType":"labels",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"30"
								}
								]
							},
							{
								"featureType":"landscape",
								"elementType":"labels.text.stroke",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							},
							{
								"featureType":"poi",
								"elementType":"geometry",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"5"
								}
								]
							},
							{
								"featureType":"poi",
								"elementType":"labels",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"30"
								}
								]
							},
							{
								"featureType":"poi",
								"elementType":"labels.text.stroke",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							},
							{
								"featureType":"road",
								"elementType":"geometry",
								"stylers":[
								{
									"visibility":"simplified"
								},
								{
									"color":"#1e242b"
								},
								{
									"lightness":"15"
								}
								]
							},
							{
								"featureType":"road",
								"elementType":"labels",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							},
							{
								"featureType":"transit",
								"elementType":"geometry",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"6"
								}
								]
							},
							{
								"featureType":"transit",
								"elementType":"labels",
								"stylers":[
								{
									"color":"#1e242b"
								},
								{
									"lightness":"30"
								}
								]
							},
							{
								"featureType":"transit",
								"elementType":"labels.text.stroke",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							},
							{
								"featureType":"water",
								"elementType":"geometry",
								"stylers":[
								{
									"color":"#010306"
								}
								]
							},
							{
								"featureType":"water",
								"elementType":"labels.text.stroke",
								"stylers":[
								{
									"visibility":"off"
								}
								]
							}
							],draggable:draggable,
							zoomControl:true,
							mapTypeControl:false,
							streetViewControl:false,
							scrollwheel:false
						};
						var map=new google.maps.Map(document.getElementById("map"),myOptions);
						var marker=new google.maps.Marker(
							{
								position:latlng,
								icon:urlImg+"img/icon-map.png",
								map:map
							}
							);
					}